UPDATE PUESTOS P SET P.DIFERENCIA =
    (SELECT DIFERENCIA FROM
        (SELECT TITULO, TO_CHAR(SUM(SALARIO/AMOUNT), 'FM999999999999999D00') PROMEDIO, DIFERENCIA FROM
            (SELECT TITULO, COUNT(SALARIO) amount, SUM(SALARIO) salario, SUM((SELECT MAX(SALARIO) FROM EMPLEADOS) - SALARIO) DIFERENCIA FROM 
                (SELECT idemp, salario, P.TITULO FROM EMPLEADOS E INNER JOIN PUESTOS P on E.IDPUESTO = P.IDPUESTO WHERE IDEMP NOT IN 
                    (SELECT DISTINCT idemp FROM EMPLEADOS WHERE IDEMP IN (SELECT IDJEFE FROM EMPLEADOS))) GROUP BY TITULO)
        T GROUP BY TITULO, DIFERENCIA) T WHERE P.TITULO = T.TITULO);
